sources:
  - .
templates:
  include:
    - .GeneratedCodeImports.stencil
    - ../Templates/AutoInit.stencil
    - ../Pods/Sourcery/Templates/AutoEquatable.stencil
    - ../Pods/Sourcery/Templates/AutoHashable.stencil
output:
   GeneratedCode.swift
